#global_costmap
global_frame: map
robot_base_frame: base_link
update_frequency: 1
publish_frequency: 1
rolling_window: false
always_send_full_costmap: false
resolution: 0.025
plugins:
   - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

