global_frame: odom
robot_base_frame: base_link
update_frequency: 1
publish_frequency: 0.5
rolling_window: true
width: 5.0
height: 5.0
resolution: 0.025
origin_x: 0
origin_y: 0

plugins:
  - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
